# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupcase',
            unique_together=set([('case', 'group')]),
        ),
    ]
