# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170224_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='auto_tag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
