# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170224_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='need_init',
            field=models.BooleanField(default=False),
        ),
    ]
