# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_config_need_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='need_init',
            new_name='init_db',
        ),
    ]
