# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20170227_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='init_group',
            field=models.BooleanField(default=True),
        ),
    ]
