# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_config_init_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='size',
        ),
        migrations.RemoveField(
            model_name='group',
            name='size',
        ),
    ]
