# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_auto_20170228_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='step',
            name='num',
        ),
        migrations.RemoveField(
            model_name='step',
            name='sleep',
        ),
        migrations.AddField(
            model_name='step',
            name='repeat',
            field=models.IntegerField(default=1),
        ),
    ]
