# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_auto_20170228_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='dataBase_host',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='dataBase_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='dataBase_port',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='dataBase_pwd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='dataBase_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
