# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_auto_20170310_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
