# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0012_auto_20170310_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='init_group',
        ),
        migrations.AlterField(
            model_name='envparam',
            name='real_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
