# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0013_auto_20170313_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='write_mode',
        ),
    ]
