# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0014_remove_config_write_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='gsdm',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
