# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0015_config_gsdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='gsdm',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
