# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0016_auto_20170313_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='request_body',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='request_query',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
